version: '3'
services:
  myapp-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=tshirt
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/mysqldata:/var/lib/mysql
  myapp-main:
    image: abdou80/tshirtdesigner_back:latest
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_PASSWORD=test
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://myapp-mysql:3306/tshirt?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
  angular-host:
      image: abdou80/tshirtdesignermfe_v:latest
      depends_on:
        - myapp-main
      ports: 
        - '4200:8082'
  angular-mfe1:
      image: abdou80/tshirtdesignerhost_v:latest
      depends_on:
        - myapp-main
      ports: 
        - '5000:5000'
    
     
  

